### PR TITLE
Override response headers to allow websites that block iframes to be linted

### PR DESCRIPTION
**Pull request by siakaramalegos**
This needs to be tested - theoretically works but I don't know how to pack the extension to get all the required properties in the manifest and scripts loaded correctly in your codebase. 

Here's a site with headers that block iframes to test with: https://performance.shopify.com/

One thing - the back button seems to go back too far.

### CODE REVIEW

**Comment by peter-neumann-dev** [comment]
@siakaramalegos Thank you for the pull request! I built the extension and your changes seem to make it work with Shopify as well in this extension. I will perform some tests on other sites and if everything is fine, I will release a new version.

**Comment by peter-neumann-dev** [comment]
> One thing - the back button seems to go back too far.

@siakaramalegos What so you mean with this?

**Comment by siakaramalegos** [comment]
After the report is done, hit the back button. I normally expect this to go
back to the page that was tested. But I think it went back two steps for
me. Sorry not at the computer right now to check if it's the same as
before.

**Comment by peter-neumann-dev** [comment]
@siakaramalegos Ah, I get it. 🙂 Yes, in the past, sometimes it did not work at all for me to go back in my browser history. I most likely clicked the link at the top.

In my current tests, it is working both on Shopify and other pages without blocking iFrames by clicking once on the history back button. 👍🏻 Maybe it is possible to open the report in a second tab, but I think this is part of [RespImageLint](https://github.com/ausi/respimagelint) itself.

**Comment by ausi** [comment]
Regarding the back button: I had to change now how the report gets displayed to fix https://github.com/ausi/respimagelint/issues/85#issuecomment-1666218134 so it is now shown inside an iframe on the same page. It now looks like a modal so the user should see that they are still on the same page.

**Comment by peter-neumann-dev** [comment]
Nice idea. I will check this out tomorrow 👍🏻

**Comment by siakaramalegos** [comment]
Just tested it out with the new version, and it's great! The modal is cool but it doesn't seem like there is a way to dismiss it

**Comment by peter-neumann-dev** [comment]
Nice 👌🏻  Yes and probably an ESC or click beside to close will also be nice to have. It could be added to[RespImageLint](https://github.com/ausi/respimagelint) itself.

**Pull request merged**
